// GET ALL POSTS
export const GET_ALL_POSTS_LOADING = "GET_ALL_POSTS_LOADING";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR="GET_ALL_POSTS_ERROR"

// POST A POST
export const POST_POST_LOADING = "POST_POST_LOADING";
export const POST_POST_SUCCESS = "POST_POST_SUCCESS";
export const POST_POST_ERROR = "POST_POST_ERROR";


// LOGIN

export const POST_LOGIN_LOADING="POST_LOGIN_LOADING"
export const POST_LOGIN_ERROR="POST_LOGIN_ERROR"
export const POST_LOGIN_SUCCESS="POST_LOGIN_SUCCESS"

// RESET_PASSWORD

export const POST_RESET_PASSWORD_LOADING="POST_RESET_PASSWORD_LOADING"
export const POST_RESET_PASSWORD_ERROR="POST_RESET_PASSWORD_ERROR"
export const POST_RESET_PASSWORD_SUCCESS="POST_RESET_PASSWORD_SUCCESS"


// GET LOCATAIRE REQUESTS

export const GET_LOCATAIRES_REQUESTS_LOADING="GET_LOCATAIRES_REQUESTS_LOADING"
export const GET_LOCATAIRES_REQUESTS_ERROR="GET_LOCATAIRES_REQUESTS_ERROR"
export const GET_LOCATAIRES_REQUESTS_SUCCESS="GET_LOCATAIRES_REQUESTS_SUCCESS"

// ACCEPT LOCATAIRE

export const POST_ACCEPT_LOCATAIRE_LOADING="POST_ACCEPT_LOCATAIRE_LOADING"
export const POST_ACCEPT_LOCATAIRE_ERROR="POST_ACCEPT_LOCATAIRE_ERROR"
export const POST_ACCEPT_LOCATAIRE_SUCCESS="POST_ACCEPT_LOCATAIRE_SUCCESS"

// REJECT LOCATAIRE

export const POST_REJECT_LOCATAIRE_LOADING="POST_REJECT_LOCATAIRE_LOADING"
export const POST_REJECT_LOCATAIRE_ERROR="POST_REJECT_LOCATAIRE_ERROR"
export const POST_REJECT_LOCATAIRE_SUCCESS="POST_REJECT_LOCATAIRE_SUCCESS"

// GET DECIDEURS PROFILES

export const GET_DECIDEURS_PROFILES_LOADING="GET_DECIDEURS_PROFILES_LOADING"
export const GET_DECIDEURS_PROFILES_ERROR="GET_DECIDEURS_PROFILES_ERROR"
export const GET_DECIDEURS_PROFILES_SUCCESS="GET_DECIDEURS_PROFILES_SUCCESS"

// TEMPLATE ACTIONS
export const TEMPLATE_SET_MENU = 'TEMPLATE_SET_MENU';
export const TEMPLATE_MENU_TOGGLE = 'TEMPLATE_MENU_TOGGLE';
export const TEMPLATE_MENU_OPEN = 'TEMPLATE_MENU_OPEN';


// SNACK BAR ACTIONS
export const SET_SNACKBAR_CONTENT="SET_SNACKBAR_CONTENT"
export const CLOSE_SNACKBAR="CLOSE_SNACKBAR"
