// GET ALL POSTS
export const GET_ALL_POSTS_LOADING = "GET_ALL_POSTS_LOADING";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR="GET_ALL_POSTS_ERROR"

// POST A POST
export const POST_POST_LOADING = "POST_POST_LOADING";
export const POST_POST_SUCCESS = "POST_POST_SUCCESS";
export const POST_POST_ERROR = "POST_POST_ERROR";


// LOGIN

export const POST_LOGIN_LOADING="POST_LOGIN_LOADING"
export const POST_LOGIN_ERROR="POST_LOGIN_ERROR"
export const POST_LOGIN_SUCCESS="POST_LOGIN_SUCCESS"

// RESET_PASSWORD

export const POST_RESET_PASSWORD_LOADING="POST_RESET_PASSWORD_LOADING"
export const POST_RESET_PASSWORD_ERROR="POST_RESET_PASSWORD_ERROR"
export const POST_RESET_PASSWORD_SUCCESS="POST_RESET_PASSWORD_SUCCESS"


// GET LOCATAIRE REQUESTS

export const GET_LOCATAIRES_REQUESTS_LOADING="GET_LOCATAIRES_REQUESTS_LOADING"
export const GET_LOCATAIRES_REQUESTS_ERROR="GET_LOCATAIRES_REQUESTS_ERROR"
export const GET_LOCATAIRES_REQUESTS_SUCCESS="GET_LOCATAIRES_REQUESTS_SUCCESS"

// ACCEPT LOCATAIRE

export const POST_ACCEPT_LOCATAIRE_LOADING="POST_ACCEPT_LOCATAIRE_LOADING"
export const POST_ACCEPT_LOCATAIRE_ERROR="POST_ACCEPT_LOCATAIRE_ERROR"
export const POST_ACCEPT_LOCATAIRE_SUCCESS="POST_ACCEPT_LOCATAIRE_SUCCESS"

// REJECT LOCATAIRE

export const POST_REJECT_LOCATAIRE_LOADING="POST_REJECT_LOCATAIRE_LOADING"
export const POST_REJECT_LOCATAIRE_ERROR="POST_REJECT_LOCATAIRE_ERROR"
export const POST_REJECT_LOCATAIRE_SUCCESS="POST_REJECT_LOCATAIRE_SUCCESS"

// GET DECIDEURS PROFILES

export const GET_DECIDEURS_PROFILES_LOADING="GET_DECIDEURS_PROFILES_LOADING"
export const GET_DECIDEURS_PROFILES_ERROR="GET_DECIDEURS_PROFILES_ERROR"
export const GET_DECIDEURS_PROFILES_SUCCESS="GET_DECIDEURS_PROFILES_SUCCESS"

// ADD DECIDEUR

export const POST_ADD_DECIDEUR_LOADING="POST_ADD_DECIDEUR_LOADING"
export const POST_ADD_DECIDEUR_ERROR="POST_ADD_DECIDEUR_ERROR"
export const POST_ADD_DECIDEUR_SUCCESS="POST_ADD_DECIDEUR_SUCCESS"

// REMOVE DECIDEUR

export const POST_TOGGLE_BLOCK_DECIDEUR_LOADING="POST_TOGGLE_BLOCK_DECIDEUR_LOADING"
export const POST_TOGGLE_BLOCK_DECIDEUR_ERROR="POST_TOGGLE_BLOCK_DECIDEUR_ERROR"
export const POST_TOGGLE_BLOCK_DECIDEUR_SUCCESS="POST_TOGGLE_BLOCK_DECIDEUR_SUCCESS"

// UPDATE DECIDEUR EMAIL
export const PUT_UPDATE_DECIDEUR_EMAIL_LOADING="PUT_UPDATE_DECIDEUR_EMAIL_LOADING"
export const PUT_UPDATE_DECIDEUR_EMAIL_ERROR="PUT_UPDATE_DECIDEUR_EMAIL_ERROR"
export const PUT_UPDATE_DECIDEUR_EMAIL_SUCCESS="PUT_UPDATE_DECIDEUR_EMAIL_SUCCESS"

export const PUT_UPDATE_DECIDEUR_PASSWORD_LOADING="PUT_UPDATE_DECIDEUR_PASSWORD_LOADING"
export const PUT_UPDATE_DECIDEUR_PASSWORD_ERROR="PUT_UPDATE_DECIDEUR_PASSWORD_ERROR"
export const PUT_UPDATE_DECIDEUR_PASSWORD_SUCCESS="PUT_UPDATE_DECIDEUR_PASSWORD_SUCCESS"

// REMOVE DECIDEUR

export const POST_REMOVE_DECIDEUR_LOADING="POST_REMOVE_DECIDEUR_LOADING"
export const POST_REMOVE_DECIDEUR_ERROR="POST_REMOVE_DECIDEUR_ERROR"
export const POST_REMOVE_DECIDEUR_SUCCESS="POST_REMOVE_DECIDEUR_SUCCESS"

// TEMPLATE ACTIONS
export const TEMPLATE_SET_MENU = 'TEMPLATE_SET_MENU';
export const TEMPLATE_MENU_TOGGLE = 'TEMPLATE_MENU_TOGGLE';
export const TEMPLATE_MENU_OPEN = 'TEMPLATE_MENU_OPEN';


// SNACK BAR ACTIONS
export const SET_SNACKBAR_CONTENT="SET_SNACKBAR_CONTENT"
export const CLOSE_SNACKBAR="CLOSE_SNACKBAR"

// GET ALL AMS  (agents de maintenance)
export const GET_ALL_AMS_LOADING = "GET_ALL_AMS_LOADING";
export const GET_ALL_AMS_SUCCESS = "GET_ALL_AMS_SUCCESS";
export const GET_ALL_AMS_ERROR="GET_ALL_AMS_ERROR";

// ADD AM

export const POST_ADD_AM_LOADING="POST_ADD_AM_LOADING";
export const POST_ADD_AM_ERROR="POST_ADD_AM_ERROR";
export const POST_ADD_AM_SUCCESS="POST_ADD_AM_SUCCESS";

// REMOVE AM

export const POST_REMOVE_AM_LOADING="POST_REMOVE_AM_LOADING";
export const POST_REMOVE_AM_ERROR="POST_REMOVE_AM_ERROR";
export const POST_REMOVE_AM_SUCCESS="POST_REMOVE_AM_SUCCESS";

// GET AM

export const GET_AM_LOADING = "GET_AM_LOADING";
export const GET_AM_SUCCESS = "GET_AM_SUCCESS";
export const GET_AM_ERROR="GET_AM_ERROR";

// GET ALL DEMANDES DE SUPPORTS 
export const GET_ALL_DEMANDESSUPPORTS_LOADING = "GET_ALL_DEMANDESSUPPORTS_LOADING";
export const GET_ALL_DEMANDESSUPPORTS_SUCCESS = "GET_ALL_DEMANDESSUPPORTS_SUCCESS";
export const GET_ALL_DEMANDESSUPPORTS_ERROR="GET_ALL_DEMANDESSUPPORTS_ERROR";

// GET ALL DEMANDES DE SUPPORTS 
export const GET_DEMANDESUPPORT_LOADING = "GET_DEMANDESUPPORT_LOADING";
export const GET_DEMANDESUPPORT_SUCCESS = "GET_DEMANDESUPPORT_SUCCESS";
export const GET_DEMANDESUPPORT_ERROR="GET_DEMANDESUPPORT_ERROR";

//GET ALL VALIDATED LOCATAIRES
export const GET_VALIDATED_LOCATAIRES_LOADING="GET_VALIDATED_LOCATAIRES_LOADING";
export const GET_VALIDATED_LOCATAIRES_ERROR="GET_VALIDATED_LOCATAIRES_ERROR";
export const GET_VALIDATED_LOCATAIRES_SUCCESS="GET_VALIDATED_LOCATAIRES_SUCCESS";

//POST REPLY SUPPORT
export const POST_REPLY_SUPPORT_LOADING="POST_REPLY_SUPPORT_LOADING";
export const POST_REPLY_SUPPORT_ERROR="POST_REPLY_SUPPORT_ERROR";
export const POST_REPLY_SUPPORT_SUCCESS="POST_REPLY_SUPPORT_SUCCESS";
 // GET REPLY SUPPORT
export const GET_ALL_REPLYDEMANDESSUPPORTS_LOADING="GET_ALL_REPLYDEMANDESSUPPORTS_LOADING";
export const GET_ALL_REPLYDEMANDESSUPPORTS_SUCCESS="GET_ALL_REPLYDEMANDESSUPPORTS_SUCCESS";
export const GET_ALL_REPLYDEMANDESSUPPORTS_ERROR="GET_ALL_REPLYDEMANDESSUPPORTS_ERROR";

//GET RESERVATIONS EN COURS
export const ENDPOINT_GET_RESERVATIONS_EN_COURS_LOADING="ENDPOINT_GET_RESERVATIONS_EN_COURS_LOADING";
export const ENDPOINT_GET_RESERVATIONS_EN_COURS_SUCCESS="ENDPOINT_GET_RESERVATIONS_EN_COURS_SUCCESS";
export const ENDPOINT_GET_RESERVATIONS_EN_COURS_ERROR="ENDPOINT_GET_RESERVATIONS_EN_COURS_ERROR";

//GET VEHICLE BY ID
export const ENDPOINT_GET_VEHICLE_ID_LOADING="ENDPOINT_GET_VEHICLE_ID_LOADING";
export const ENDPOINT_GET_VEHICLE_ID_SUCCESS="ENDPOINT_GET_VEHICLE_ID_SUCCESS";
export const ENDPOINT_GET_VEHICLE_ID_ERROR="ENDPOINT_GET_VEHICLE_ID_ERROR";