// GET ALL POSTS
export const GET_ALL_POSTS_LOADING = "GET_ALL_POSTS_LOADING";

export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR="GET_ALL_POSTS_ERROR"

// POST A POST
export const POST_POST_LOADING = "POST_POST_LOADING";
export const POST_POST_SUCCESS = "POST_POST_SUCCESS";
export const POST_POST_ERROR = "POST_POST_ERROR";
